# Generated by Django 6.0.5 on 2026-06-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код комнаты')),
                ('x', models.IntegerField(default=0, verbose_name='Координата X')),
                ('y', models.IntegerField(default=0, verbose_name='Координата Y')),
                ('width', models.IntegerField(default=100, verbose_name='Ширина')),
                ('height', models.IntegerField(default=100, verbose_name='Высота')),
                ('floor', models.PositiveSmallIntegerField(default=1, verbose_name='Этаж')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'ordering': ['floor', 'name'],
            },
        ),
    ]
