# Generated by Django 6.0.5 on 2026-06-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код комнаты')),
                ('coordinates', models.TextField(verbose_name='SVG-путь (polygon points)')),
                ('floor', models.PositiveSmallIntegerField(default=1, verbose_name='Этаж')),
                ('fill_color', models.CharField(default='#f0f0f0', max_length=7, verbose_name='Цвет заливки')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'ordering': ['floor', 'name'],
            },
        ),
    ]
