# Generated by Django 6.0.5 on 2026-06-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='label_x',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Позиция названия X'),
        ),
        migrations.AddField(
            model_name='room',
            name='label_y',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Позиция названия Y'),
        ),
        migrations.AlterField(
            model_name='room',
            name='fill_color',
            field=models.CharField(default='#f8f8f8', max_length=7, verbose_name='Цвет заливки'),
        ),
    ]
